kubeflow/metadata

- OWNERS
OWNERS file is not functional without the Yaml fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/1)
> Fix Yaml formatting

- roadmap.md
List the plan for v0.6 release. Issues will be created for these items.
/cc @neuromage @jlewi @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/2)
> Roadmap for v0.6

- Dockerfile
First step of #11 installing metadata as KF component.
Tested it locally.
/cc @neuromage @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/16)
> Add Dockerfile for building service image

- server/main.go
The return value should be checked.
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/21)
> Check return value of http.ListenAndServe

- third_party/ml_metadata/README.md
I forgot to add this file to my commit after making changes in response to code review comments in PR #30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/32)
> Add third_party/ml_metadata README file.

- third_party/ml_metadata/metadata_store/metadata_store_go_wrap/metadata_store_go_wrap.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/34)
> Fix CGO flags for running  on Linux

- python_client/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/39)
> add myself to the reviews of the python packages

- Dockerfile
Update Dockerfile to build image with Bazel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/36)
> Use bazel to build docker image

- Makefile
- server/main.go
Tested it locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/42)
> Add MySql password flag

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/46)
> Added issue/pr template.

- README.md
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/51)
> add bazel version info

- api/generate_proto.sh
- api/service.swagger.json
- sdk/python/kfmd/metadata.py
- service/service.go
- Fixes #55 to avoid HTTP path overlap.
- Reduce the assumption of #maximum type stored in the database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/58)
> Update swagger generation script to avoid duplicated HTTP path

- service/service.go
- service/service_test.go
**Which issue(s) this PR fixes** 
Fixes https://github.com/kubeflow/metadata/issues/63
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/64)
> ListArtifacts should return an empty list if no artifacts exists

- schemaparser/register.go
- test/e2e/make_requests.sh
This PR registers the predefined execution type during server start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/66)
> Register predefined execution type

- frontend/__mocks__/typestyle.ts
- frontend/src/atoms/Input.test.tsx
- frontend/src/atoms/Input.tsx
- frontend/src/atoms/Separator.tsx
- frontend/src/atoms/__snapshots__/BusyButton.test.tsx.snap
- frontend/src/atoms/__snapshots__/Input.test.tsx.snap
- frontend/src/components/CustomTable.test.tsx
- frontend/src/components/CustomTable.tsx
- frontend/src/components/__snapshots__/ArtifactInfo.test.tsx.snap
- frontend/src/components/__snapshots__/Banner.test.tsx.snap
- frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
- frontend/src/components/__snapshots__/ModelInfo.test.tsx.snap
- frontend/src/components/__snapshots__/Router.test.tsx.snap
- frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
- frontend/src/lib/Api.ts
- frontend/src/pages/ArtifactList.test.tsx
- frontend/src/pages/ArtifactList.tsx
- frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
- frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
closes #70 
/area frontend
/cc @rileyjbauer 
Adds sorting and filtering to ArtifactsList page in a manner consistent with adding server-side handling of these features in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/72)
> Add client-side sorting and filtering

- sdk/python/demo.ipynb
- sdk/python/kfmd/metadata.py
- sdk/python/tests/test.py
Fixes #60 #6 
The actual changes are on the Python SDK:
- Expose the `Execution` object to `log_input` or `log_output`
- Make `Run` a simple grouping concept.
- Update the [notebook example ](https://github.com/zhenghuiwang/metadata/blob/cec82de6a1d6f33d9258929195f80698910a0857/sdk/python/demo.ipynb)to reflect this change and add a section of lineage tracking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/69)
> Add lineage tracking into Python SDK

- sdk/python/setup.py
Update the `setup.py` for pushing the new python SDK release.
`0.1.6` is already push to PyPI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/83)
> Update python SDK version

- schema/alpha/docs/artifacts/model.md
Typo fix
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/85)
> Typo fix in model.md

- test/scripts/create-cluster.sh
- test/workflows/app.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/90)
> Fix e2e test

- frontend/Dockerfile
- frontend/package.json
- frontend/src/components/CustomTable.test.tsx
- frontend/src/components/CustomTable.tsx
- frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
- frontend/src/pages/ArtifactList.test.tsx
- frontend/src/pages/ArtifactList.tsx
- frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
Copied from #82 in order to merge in a test fix while @prodonjs is out of office.
Adds grouping and expansion to Artifacts List view in accordance with UX mocks.
*Which issue(s) this PR fixes**
Fixes #71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/95)
> Adds grouping/expansion to Artifacts List view - Copied from #82

- schemaparser/register.go
Fixes #94
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/92)
> update some logs

- service/service_test.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/100)
> change a variable name

- Dockerfile
- dockerfiles/Dockerfile-linux-base
- Split the dockerfile so that different base images can be used.
- Improve efficiency: prebuild a base image so that e2e tests don't have build images from scratch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/104)
> Split the dockerfile

- frontend/src/apis/service/api.ts
Updates frontend API definitions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/112)
> Regenerates swagger APIs

- frontend/server/server.ts
- frontend/src/Css.tsx
- frontend/src/components/ArtifactInfo.tsx
- frontend/src/components/CustomTable.tsx
- frontend/src/components/__snapshots__/ArtifactInfo.test.tsx.snap
- frontend/src/lib/Utils.ts
- frontend/src/pages/ArtifactDetails.tsx
- frontend/src/pages/ArtifactList.test.tsx
- frontend/src/pages/ArtifactList.tsx
- frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
- frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
Displays all properties and custom properties in details page instead of only a specific subset.
Also removes expansion button from rows when there aren't multiple versions of an artifact
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/111)
> Displays all properties and custom properties in details page

- sdk/python/kfmd/metadata.py
- sdk/python/tests/test.py
Add some code for checking the necessary input arguments in python sdk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/122)
> improve the necessary input arguments checking for python

- frontend/src/components/Router.tsx
- frontend/src/pages/ArtifactList.test.tsx
- frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/124)
> Fix execution details routing

- WORKSPACE
Update ml_metadata reference to latest commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/130)
> Update ml_metadata reference to latest commit

- .gitignore
- Makefile
- sdk/OWNERS
- sdk/python/README.md
- sdk/python/build.sh
- sdk/python/kubeflow/__init__.py
- sdk/python/kubeflow/metadata/metadata.py
- sdk/python/sample/demo.ipynb
- sdk/python/setup.py
- sdk/python/tests/run_tests.sh
- sdk/python/tests/test.py
Rename SDK to kubeflow-metadata, see more in #106 
Fixes #106
```release-note
The python SDK pacakge is renamed to " kubeflow-metadata"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/131)
> Rename SDK to kubeflow-metadata

- frontend/OWNERS
**What this PR does / why we need it**: update owner
Hi, I'm the engineer to follow up on @rileyjbauer's work from kubeflow/pipelines team.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/144)
> Add Bobgy to frontend approver and reviewer

- WORKSPACE
Update MLMD version to 0.15.1 with bug fixes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/169)
> Update MLMD version to 0.15.1 with bug fixes

- frontend/gen_grpc_web_protos.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/ArtifactList.tsx
- frontend/src/pages/LineageView.tsx
- Fixed basic linter issues
- Updated small parts of the scripts to run on windows
/area metadata
/priority p1
/cc @kwasi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/175)
> Fixed linter issues, and updated scripts to work on windows

- test/e2e/Make-Requests.ps1
- Created a PowerShell script to generate data identically to its bash counterpart
- This data populates the MLMD viewer with artifacts
/area metadata
/priority p1
/cc @kwasi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/176)
> Created a powershell script to generate data identically to its bash counterpart

- frontend/docker_build.js
Follow up to #180 with nits resolved
/area metadata
/priority p1
/cc @kwasi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/181)
> [Windows] Follow up to #180 with nits resolved

- sdk/python/sample/demo.ipynb
A few quick spelling nits on the demo notebook for MLMD SDK.
/area metadata
/priority p1
/cc @kwasi @zhenghuiwang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/186)
> MLMD SDK Notebook spelling nits

- sdk/python/sample/demo.ipynb
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/197)
> Fix typo in demo.ipynb

- third_party/library/license.txt
Update license.txt to pull in license updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/205)
> Update the license.txt

- OWNERS
Added @avdaredevil and @kwasi as maintainers of metadata
/area metadata
/priority p0
/assign @abhi-g @jlewi @zhenghuiwang 
/cc @kwasi @avdaredevil
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/209)
> [MLMD] [Perms] Added me and @kwasi as owners of metadata

- frontend/server/server.ts
- Server linting errors fixed
- Errors removed
- Updated error checking to take place before `express()` initialization
- Condensed import statements
- Types added to TS file: Variables, Function typedefs, calls, function -> lambdas
/area metadata
/priority p1
/cc @kwasi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/210)
> [MLMD] Refactored server TS code

- sdk/python/README.md
- sdk/python/kubeflow/metadata/metadata.py
- sdk/python/setup.py
- sdk/python/tests/run_tests.sh
- sdk/python/tests/test_metadata.py
- third_party/library/license.txt
Fixes #212
**This PR becomes unexpectedly large to include fixes of the presubmit tests.**
Fixes #213 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/215)
> Fix broken links and update dependencies

- frontend/package-lock.json
- frontend/package.json
- frontend/src/TestUtils.ts
- frontend/src/atoms/MD2Tabs.test.tsx
- frontend/src/atoms/MD2Tabs.tsx
- frontend/src/components/CustomTable.tsx
- frontend/src/components/ModelInfo.test.tsx
- frontend/src/components/ModelInfo.tsx
- frontend/src/components/ResourceInfo.test.tsx
- frontend/src/components/ResourceInfo.tsx
- frontend/src/lib/Utils.tsx
- frontend/src/pages/ArtifactDetails.test.tsx
- frontend/src/pages/ArtifactDetails.tsx
- frontend/src/pages/ArtifactList.test.tsx
- frontend/src/pages/ArtifactList.tsx
- frontend/src/pages/ExecutionDetails.tsx
- frontend/src/pages/ExecutionList.tsx
Updated metadata to master upstream changes from [`kubeflow/frontend`](https://github.com/kubeflow/frontend), refactored imports
- This is the prereq change before I upstream element updates from [`kubeflow/pipelines`](https://github.com/kubeflow/pipelines) that are not part of the shared elements
/area metadata
/priority p0
/cc @kwasi @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/metadata/216)
> [MLMD] Final updates to lineage view
